services:
  app:
    # 開発用
    container_name: dev-sample-app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER:-ubuntu}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - .:/workspace # ソースをマウント
      - app-home:/home/${USER} # ホームディレクトリの永続化
      - ${USER_SSH:-./docker/app/.ssh}:/home/${USER}/.ssh:ro # SSH設定
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: /bin/bash
    depends_on:
      - db

  db:
    container_name: dev-sample-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd123
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: sql@pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  app-home:
  db-data:
